<a href="https://colab.research.google.com/github/mohammadreza76/cancer_detection/blob/master/cancer_detection_with_multiple_algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [ ]:
import numpy as np  # for handling multi-dimensional array operation
import pandas as pd  # for reading data from csv 
from sklearn.preprocessing import StandardScaler, LabelEncoder  # for normalization
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix 
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel

## Importing the dataset

In [ ]:
data = pd.read_csv('datasets_180_408_data.csv',index_col = False) 

In [ ]:
data.head(3)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN

[3 rows x 33 columns]

## Preprocessing data

In [ ]:
X = data.iloc[:,2:-1].values
y = data.iloc[:,1].values

Encoding the Dependent Variable

In [ ]:
label_encode = LabelEncoder()
y = label_encode.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.25, random_state = 42)

## Feature Scaling

In [ ]:
standard_scale = StandardScaler()
X_train = standard_scale.fit_transform(X_train)
X_test = standard_scale.transform(X_test)

## Training the SVM model on the training set

In [ ]:
svm_model = SVC(kernel= 'rbf')
svm_model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## Training the Logistic regression model on the training set

In [ ]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the Test set results in SVM model

In [ ]:
y_predict_svm = svm_model.predict(X_test)
y_predict_svm = label_encode.fit_transform(y_predict_svm)
print(np.concatenate((y_test.reshape(len(y_test),1),y_predict_svm.reshape(len(y_predict_svm),1)),axis = 1))

[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]

In [ ]:
Confusion_matrix = confusion_matrix(y_test,y_predict_svm)
print(Confusion_matrix)
accuracy_score(y_test,y_predict_svm)

[[87  2]
 [ 2 52]]


0.972027972027972

## Predicting the Test set results in Logistic regression model

In [ ]:
y_predict_logistic = logistic_model.predict(X_test)
y_predict_logistic = label_encode.fit_transform(y_predict_logistic)

In [ ]:
Confusion_matrix = confusion_matrix(y_test,y_predict_logistic)
print(Confusion_matrix)
accuracy_score(y_test,y_predict_logistic)

[[87  2]
 [ 1 53]]


0.9790209790209791

## Use feature selecting and then predict with logistic regression

In [ ]:
X.shape

(569, 30)

## feature selection

In [ ]:
model_logistic = SelectFromModel(logistic_model, prefit=True)
X_new = model_logistic.transform(X)

In [ ]:
X_new.shape

(569, 14)

## Splitting the dataset into the Training set and Test set

In [ ]:
X_train_new,X_test_new,y_train_new,y_test_new = train_test_split(X_new,y,test_size= 0.25, random_state = 42)

In [ ]:
X_train_new.shape

(426, 14)

## Feature Scaling

In [ ]:
standard_scale = StandardScaler()
X_train = standard_scale.fit_transform(X_train_new)
X_test = standard_scale.transform(X_test_new)

## Training the Logistic regression model on the new training set(with feature selection)

In [ ]:
logistic_model_new = LogisticRegression(max_iter= 300)

In [ ]:
logistic_model_new.fit(X_train_new,y_train_new)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the new Test set results in new Logistic regression model

In [ ]:
y_predict_logistic_new = logistic_model_new.predict(X_test_new)
Confusion_matrix = confusion_matrix(y_test,y_predict_logistic_new)
print(Confusion_matrix)
accuracy_score(y_test,y_predict_logistic_new)

[[87  2]
 [ 3 51]]


0.965034965034965